### ISSUE TITLE
TODO 2017/10

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#21]
10/05

- [x] Polish up https://github.com/rbind/blogdown-demo
- [x] Document blogdown functions https://github.com/rstudio/blogdown/issues/206
- [x] Summarize Amber's Google doc on the blogdown book into action items

**Comment by yihui** [comment]
10/06

- [x] An introductory chapter on R Markdown https://github.com/rstudio/blogdown/issues/207. Hoping to get it done in one day...

**Comment by yihui** [comment]
10/09

- [x] What to do with `knitr:::wrap()`: https://github.com/yihui/knitr/issues/1442 should I rename it before exporting it?
- [x] Figure out a _reasonable_ plan for the [rmarkdown 1.17](https://github.com/rstudio/rmarkdown/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.7) release.
- [x] A letter for Brooke.

**Comment by yihui** [comment]
10/10

- [x] Cut 97 rmarkdown issues to 86.
- [x] Finish the Acknowledgements section of the blogdown book (attribute Sharon Machlis for https://github.com/rstudio/blogdown/issues/193, and Taras Kaduk and Angelina Kaduk for the logo)
- [x] Review https://github.com/rstudio/reticulate/pull/107

**Comment by yihui** [comment]
10/11

- [x] Prepare [the talk for CGM](http://cgmonline.co/2017/10/cgm-%E7%AC%AC16%E6%9C%9F%E7%94%A8-blogdown-%E6%90%AD%E5%BB%BA%E4%B8%80%E4%B8%AA%E9%9D%99%E6%80%81%E7%BD%91%E7%AB%99/).
- [x] Kevin asked:
    > is there a preferred way for engines that produce plot output to implement the figure counter (`fig.cur`)? it looks like `plot_counter()` is the internal `knitr` API, but I wonder if there's something else I could / should be doing (basically, I have the graphics device in such a place where I can tell it to give me a `.png`, and then I wrap that up in `include_graphics()` -- but I'd like to respect some of the `fig.*` options if possible)
- [x] https://github.com/yihui/knitr/issues/1443

**Comment by yihui** [comment]
10/12

- [x] Review https://github.com/cosname/cosx.org/pull/713
- [x] https://github.com/yihui/knitr/pull/1444
- [x] https://github.com/rstudio/rmarkdown/issues/989
- [x] https://github.com/rstudio/rmarkdown/issues/1154
- [x] https://github.com/rstudio/rmarkdown/issues/1152

**Comment by yihui** [comment]
10/13

- [x] Cut the number of rmarkdown issues to 73.

**Comment by yihui** [comment]
10/16

- [x] Review Jeff's doc.
- [x] https://github.com/rstudio/blogdown/pull/219
- [x] Continue working on rmarkdown issues (61 left).

**Comment by yihui** [comment]
10/17

- [x] https://github.com/rstudio/blogdown/pull/219
- [x] Test pandoc with PPT.
- [x] https://github.com/rstudio/rmarkdown/pull/820

**Comment by yihui** [comment]
10/18

- [x] Revise one rec letter.
- [x] Continue working on rmarkdown issues.

**Comment by yihui** [comment]
10/19

- [x] Continue working on rmarkdown issues.

**Comment by yihui** [comment]
10/20

- [x] Build the latest version of Pandoc via CI: https://github.com/yihui/travis-bin

**Comment by yihui** [comment]
10/22

- [x] remark.js macros in xaringan: https://github.com/yihui/xaringan/issues/80

**Comment by yihui** [comment]
10/23

- [x] Test the latest version of Pandoc against rmarkdown.
- [x] Work on rmarkdown 1.17 issues.

**Comment by yihui** [comment]
10/24

- [x] Work on rmarkdown 1.17 issues.
- [x] A short blog post on tidyverse and base R.

**Comment by yihui** [comment]
10/25

- [x] Fixes https://github.com/rstudio/blogdown/issues/222
- [x] Work on rmarkdown 1.17 issues.

**Comment by yihui** [comment]
10/26

- [x] Work on rmarkdown 1.17 issues.
- [x] Implement [pagination](https://gohugo.io/templates/pagination/) in hugo-xmin and mention it in the blogdown book.

**Comment by yihui** [comment]
10/27

- [x] xaringan themes

**Comment by yihui** [comment]
10/30

- [x] https://github.com/rstudio/blogdown/pull/223
- [x] https://github.com/jgm/pandoc/releases/tag/2.0
- [x] Review Jeff's doc.
- [x] Revise the blogdown book according to the proofreader's comments.

**Comment by yihui** [comment]
10/31

- [x] https://github.com/rstudio/rmarkdown/issues/590
- [x] blogdown book: fix single-line pages (acknowledgments and bibliography); add cover image
