### ISSUE TITLE
TODO 2017/11

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#29]
11/01

- [x] https://github.com/rstudio/blogdown/pull/225
- [x] Release blogdown v0.2 https://github.com/rstudio/blogdown/issues/224
- [x] https://github.com/yihui/xaringan/pull/76 https://github.com/yihui/xaringan/pull/86

**Comment by yihui** [comment]
11/02

- [x] Slides for the UNL seminar on bookdown, blogdown, and xaringan.
- [x] Complete the blogdown book back cover.

**Comment by yihui** [comment]
11/03

- [x] The UNL seminar #30.
- [x] https://github.com/rstudio/blogdown/pull/225

**Comment by yihui** [comment]
11/06

- [x] Finalize the blogdown book.
- [x] highlight.js in rmarkdown https://github.com/rstudio/rmarkdown/pull/1178
    - https://github.com/rstudio/highlight.js/commit/061f39aec4b39ae65a756e1bf10d51f076872207
    - https://github.com/isagalaev/highlight.js/blob/master/src/languages/r.js

**Comment by yihui** [comment]
11/07

- [x] https://github.com/rstudio/rmarkdown/pull/1178

**Comment by yihui** [comment]
11/08

- [x] https://github.com/rstudio/flexdashboard/issues/149
- [x] https://github.com/rstudio/bookdown/issues/479

**Comment by yihui** [comment]
11/09

- [x] rmarkdown 1.7 PRs https://github.com/rstudio/rmarkdown/pulls?q=is%3Aopen+is%3Apr+milestone%3Av1.7
- [x] Submit rmarkdown 1.7 to CRAN.

**Comment by yihui** [comment]
11/10

- [x] https://github.com/rstudio/rmarkdown/issues/1189
- [x] https://github.com/rstudio/rmarkdown/issues/1193

**Comment by yihui** [comment]
11/13

- [x] https://github.com/rstudio/rmarkdown/issues/1197
- [x] Review Jeff's doc.

**Comment by yihui** [comment]
11/14

- [x] More on Jeff's doc
- [x] https://github.com/rstudio/rmarkdown/issues/1200
- [x] https://github.com/rstudio/bookdown/issues/483
- [x] Revise another rec letter.

**Comment by yihui** [comment]
11/15

- [x] Explain to the RSC team why `local(rmarkdown::run())` is not a good idea.

**Comment by yihui** [comment]
11/16

- [x] Explained why `rmarkdown::run(render_args = list(envir = globalenv()))` is necessary.
- [x] https://github.com/rstudio/bookdown/issues/485

**Comment by yihui** [comment]
11/17

- [x] https://github.com/rstudio/flexdashboard/issues/155
- [x] Submit rmarkdown 1.8 to CRAN.
- [x] https://github.com/rstudio/blogdown/issues/230
- [x] Integrate `reticulate::eng_python()` in knitr.
- [x] https://github.com/yihui/knitr/issues/1460

**Comment by yihui** [comment]
11/18

- [x] https://github.com/yihui/knitr/issues/1458
- [x] https://github.com/rstudio/rstudio/issues/1752

**Comment by yihui** [comment]
11/20

- [x] workaround for Hugo's Fast Render Mode in `blogdown::new_post()` (does not work well when creating new posts); must I use `--disableFastRender`?
- [x] https://github.com/rstudio/rmarkdown/issues/1184%5B#issuecomment-345624157%5D(/tag?tag=issuecomment-345624157)

**Comment by yihui** [comment]
11/21

- [x] https://github.com/rstudio/learnr/issues/133
- [x] https://github.com/yihui/knitr/issues/1462
- [x] https://github.com/yihui/knitr/issues/1456
- [x] https://github.com/yihui/knitr/issues/1455
- [x] https://github.com/yihui/knitr/issues/1448 https://github.com/yihui/knitr/pull/1449
- [x] https://github.com/rstudio/blogdown/issues/232
- [x] Pandoc 2.0 issues that just won't die https://community.rstudio.com/t/3019
- [x] https://github.com/yihui/knitr/pull/1444

**Comment by yihui** [comment]
11/22

- [x] Change the regexp for inline expressions in knitr? e.g. ``` `` `r ` `` ``` should not be parsed and executed.
- [x] Start working on https://github.com/yihui/tinytex

**Comment by yihui** [comment]
11/27

- [x] tinytex: shell scripts for macOS

**Comment by yihui** [comment]
11/28

- [x] tinytex: Homebrew formula, shell scripts for Linux

**Comment by yihui** [comment]
11/29

- [x] tinytex: batch script for Windows (terrible!)

**Comment by yihui** [comment]
11/30

- [x] The R package tinytex
