### ISSUE TITLE
TODO 2017/12

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#31]
12/01

- [x] The R package tinytex

**Comment by yihui** [comment]
12/04

- [x] Soft launch tinytex via a personal blog post

**Comment by yihui** [comment]
12/05

- [x] yihui/tinytex#1

**Comment by yihui** [comment]
12/06

- [x] monthly summary
- [x] more tinytex improvements

**Comment by yihui** [comment]
12/07

- [x] submit tinytex to CRAN

**Comment by yihui** [comment]
12/08

- [x] rstudio::conf travel arrangements

**Comment by yihui** [comment]
12/11

- [x] `rmarkdown::render()` attach metadata https://github.com/rstudio/rmarkdown/pull/1199

**Comment by yihui** [comment]
12/12

- [x] https://github.com/rstudio/rmarkdown/tree/feature/powerpoint

**Comment by yihui** [comment]
12/13

- [x] Tweaked the installation of TinyTeX on Windows

**Comment by yihui** [comment]
12/18

- [x] lawyer

**Comment by yihui** [comment]
12/19

- [x] lawyer again
- [x] a blog post to summarize my 2017
- [x] tinytex 0.2 to CRAN

**Comment by yihui** [comment]
12/20

- [x] 《中国大百科全书》统计图形条目
- [x] https://github.com/rstudio/bookdown/pull/498
- [x] lawyer, again
- [x] Figure out why `fig.link` and `include_app()` do not work for PPT output.
- [x] PowerPoint support in rmarkdown with [Pandoc 2.0.5](https://github.com/jgm/pandoc/releases/tag/2.0.5)

**Comment by yihui** [comment]
12/21

- [x] figure out why [travis failed for knitr](https://travis-ci.org/yihui/knitr/jobs/319550653)

**Comment by yihui** [comment]
12/22

- [x] https://github.com/yihui/printr/issues/33
