### ISSUE TITLE
TODO 2018/01

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#34]
01/02

- [x] https://github.com/rstudio/rmarkdown/pull/1231
- [x] https://github.com/rstudio/rmarkdown/issues/1005
- [x] https://cran.r-project.org/web/packages/pixiedust/index.html

**Comment by yihui** [comment]
01/03

- [x] https://github.com/rstudio/DT/issues/471
- [x] https://github.com/rstudio/DT/issues/116
- [x] https://github.com/rstudio/DT/issues/421

**Comment by yihui** [comment]
01/04

- [x] https://github.com/rstudio/DT/issues/198

**Comment by yihui** [comment]
01/05

- [x] Process DT issues https://github.com/rstudio/DT/issues

**Comment by yihui** [comment]
01/05

- [x] https://github.com/rstudio/DT/issues

**Comment by yihui** [comment]
01/08

- Sick leave

**Comment by yihui** [comment]
01/09

- Sick leave

**Comment by yihui** [comment]
01/10

- [x] https://github.com/rstudio/rticles/pull/148
- [x] https://github.com/yihui/knitr/issues/1489 https://github.com/yihui/knitr/blob/master/R/output.R
- [x] https://github.com/rstudio/rmarkdown/pull/1231

**Comment by yihui** [comment]
01/15

- [x] https://github.com/yihui/xfun
- [x] https://github.com/rstudio/DT/pull/475
- [x] https://github.com/rstudio/DT/issues

**Comment by yihui** [comment]
01/16

- [x] https://github.com/rstudio/DT/issues/464
- [x] https://github.com/rstudio/DT/issues/457
- [x] https://github.com/rstudio/DT/issues/454
- [x] https://github.com/rstudio/DT/issues/438
- [x] https://github.com/rstudio/DT/issues/379
- [x] https://github.com/rstudio/DT/issues/359

**Comment by yihui** [comment]
01/17

- [x] https://github.com/rstudio/DT/issues/481
- [x] https://github.com/rstudio/DT/issues/28

**Comment by yihui** [comment]
01/18

- [x] https://github.com/rstudio/DT/issues/453

**Comment by yihui** [comment]
01/19

- [x] https://github.com/yihui/tinytex/issues/14
- [x] Update DT documentation

**Comment by yihui** [comment]
01/22

- [x] Release xfun: https://cran.rstudio.com/package=xfun
- [x] Release tinytex 0.3: https://cran.rstudio.com/package=tinytex

**Comment by yihui** [comment]
01/23

- [x] release DT 0.3
- [x] https://github.com/rstudio/tufte/issues/52
- [x] https://github.com/rstudio/bookdown/issues/521

**Comment by yihui** [comment]
01/24

- [x] release blogdown 0.5 (waiting xfun's Windows binary to be available)
- [x] release tufte 0.3
- [x] release bookdown 0.6 (after blogdown is on CRAN)
- [x] https://github.com/rstudio/DT/issues/488

**Comment by yihui** [comment]
01/25

- [x] rviews help
- [x] https://github.com/rstudio/DT/pull/487
- [x] https://github.com/rstudio/rmarkdown/issues/1238
- [x] https://github.com/rstudio/rmarkdown/issues/1247
- [x] think about the rmarkdown release 1.9 https://github.com/rstudio/rmarkdown/issues

**Comment by yihui** [comment]
01/29

- [x] release knitr 1.19
- [x] https://github.com/yihui/knitr/pull/1484
- [x] https://github.com/yihui/xaringan/pull/103
- [x] release xaringan v0.5

**Comment by yihui** [comment]
01/30

- [x] rstudio::conf presentation

**Comment by yihui** [comment]
01/31

- [x] rstudio::conf presentation
