### ISSUE TITLE
TODO 2018/02

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#38]
02/01 - 04

- [x] rstudio::conf at San Diego.

**Comment by yihui** [comment]
02/05 - 09

- [x] Get started with the rmarkdown book https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/12 -16

- [x] Chapter 1 https://github.com/rstudio/rmarkdown-book
- [x] Finish the post I have been hoping to write for a long time https://yihui.name/en/2018/02/career-crisis/

**Comment by yihui** [comment]
02/19

- [x] https://github.com/yihui/xaringan/pull/113
- [x] Submit knitr 1.20 to CRAN (to fix vignette problems caused by 1.19 to a few CRAN packages, as requested by Kurt)
- [x] Quick responses to a lot of responses to my recent blog post

**Comment by yihui** [comment]
02/20

- [x] Submit rmarkdown 1.9 to CRAN again since the previous submission was lost
- [x] Section 2.1 - 2.4 https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/21

- [x] Section 2.5 - 2.7 https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/22

- [x] Finish Chapter 2 https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/23

- [x] Section 3.1 https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/26

- [x] https://github.com/rstudio/DT/pull/514
- [x] https://github.com/rstudio/DT/pull/513
- [x] https://github.com/rstudio/blogdown/pull/263

**Comment by yihui** [comment]
02/27

- [x] Section 3.2 https://github.com/rstudio/rmarkdown-book

**Comment by yihui** [comment]
02/28

- [x] Section 3.3 - 3.6 https://github.com/rstudio/rmarkdown-book
