### ISSUE TITLE
TODO 2018/03

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#44]
03/16

- [x] Section 4.1 of the R Markdown book

**Comment by yihui** [comment]
03/19

- [x] https://github.com/rstudio/rmarkdown/issues/1285 https://github.com/yihui/tinytex/issues/28

**Comment by yihui** [comment]
03/20

- [x] Section 4.2 and 4.3 of the R Markdown book

**Comment by yihui** [comment]
03/21

- [x] Section 4.4 of the R Markdown book

**Comment by yihui** [comment]
03/26

- [x] Prep slides for the Omaha R User Group

**Comment by yihui** [comment]
03/27

- [x] Talk about R Markdown and dashboards at the Omaha R User Group

**Comment by yihui** [comment]
03/28

- [x] https://github.com/yihui/tinytex/issues/29
- [x] Test Pandoc 2.1.3 bundled with RStudio daily (and made some aesthetic changes in bookdown)
- [x] DT blog post

**Comment by yihui** [comment]
03/29

- [x] https://github.com/yihui/tinytex/issues/32
- [x] https://github.com/rstudio/rmarkdown/issues/1289

**Comment by yihui** [comment]
03/30

- [x] https://github.com/yihui/knitr/pull/1518
