### ISSUE TITLE
TODO 2018/04

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#45]
04/02

- [x] https://github.com/rstudio/blogdown/pull/288

**Comment by yihui** [comment]
04/03

- [x] Chapter 5 of the R Markdown book

**Comment by yihui** [comment]
04/04

- [x] Chapter 6 of the R Markdown book

**Comment by yihui** [comment]
04/05

- [x] Chapter 7 of the R Markdown book

**Comment by yihui** [comment]
04/06

- [x] https://github.com/rstudio/DT/pull/522
- [ ] https://github.com/rstudio/rticles/pull/161

**Comment by yihui** [comment]
04/09

- [x] Chapter 8 of the R Markdown book

**Comment by yihui** [comment]
04/11

- [x] https://github.com/rstudio/DT/pull/522

**Comment by yihui** [comment]
04/16

- [x] Chapter 9 of the R Markdown book

**Comment by yihui** [comment]
04/17

- [x] Chapter 10 of the R Markdown book

**Comment by yihui** [comment]
04/19

- [x] https://github.com/yihui/knitr/pull/1518
- [x] https://github.com/rstudio/rmarkdown-book/pull/4 (Chapter 12 of the R Markdown book)

**Comment by yihui** [comment]
04/20

- [x] Chapter 11 of the R Markdown book

**Comment by yihui** [comment]
04/23

- [x] Chapter 13 of the R Markdown book

**Comment by yihui** [comment]
04/24

- [x] https://github.com/rstudio/DT/pull/532
- [x] Chapter 15 of the R Markdown book

**Comment by yihui** [comment]
04/30

- [x] https://github.com/rstudio/rmarkdown-book/pull/10
- [x] https://stackoverflow.com/q/50098235/559676
