### ISSUE TITLE
TODO 2018/05

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#46]
05/01

- [x] Chapter 18 of the R Markdown book

**Comment by yihui** [comment]
05/15

- [x] Announce PPT in RStudio Community.
- [x] Look at Radix.

**Comment by yihui** [comment]
05/16

- [x] Respond to rmarkdown book reviews.

**Comment by yihui** [comment]
05/17

- [x] Complete the section "Structure of the book", and explain how to read this book. This will set the correct expectation of readers.

**Comment by yihui** [comment]
05/18

- [x] Try to minimize the tiny technical details in Chapter 2.

**Comment by yihui** [comment]
05/23

- [x] Provide a list of interesting examples and applications in Chapter 2 before diving into the technology.

**Comment by yihui** [comment]
05/29

- [x] Add more community formats in the R Markdown book.
- [x] Add more screenshots.
- [x] Read Tareef's reviews.

**Comment by yihui** [comment]
05/30

- [x] A draft of acknowledgements.

**Comment by yihui** [comment]
05/31

- [x] Back-cover copy and chapter abstracts of the R Markdown book.
- [x] Redirect some rmarkdown web pages to the rmarkdown book https://github.com/rstudio/rmarkdown/pull/1350
