### ISSUE TITLE
TODO 2018/06

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#47]
06/05

- [x] Investigate the Pandoc 2.2.1 issue on CRAN.

**Comment by yihui** [comment]
06/06 - 06/07

- [x] A repo for Homebrew binary R packages: https://github.com/yihui/homebrew-r-packages

**Comment by yihui** [comment]
06/08 - 06/09

- [x] Prepare rmarkdown 1.10 release.

**Comment by yihui** [comment]
06/11

- [x] Prepare the [RaukR](https://www.scilifelab.se/events/raukr-advanced-r-for-bioinformatics-summer-school/) talk.

**Comment by yihui** [comment]
06/12

- [x] Give the remote talk to RaukR.

**Comment by yihui** [comment]
06/13 - 14

- [x] A homepage for https://github.com/yihui/homebrew-r-packages

**Comment by yihui** [comment]
06/18

- [x] Finish the revision of the R Markdown book required by the copy-editor.

**Comment by yihui** [comment]
06/20

- [x] https://github.com/yihui/knitr/issues/1558

**Comment by yihui** [comment]
06/25

- [x] rmarkdown issues
- [x] a plan for what to do next

**Comment by yihui** [comment]
06/28

- [x] https://github.com/rstudio/rmarkdown/pull/1350

**Comment by yihui** [comment]
06/29

- [x] Use [`r-app`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/r-app.rb) to build the missing macOS binary R packages on CRAN
