### ISSUE TITLE
TODO 2018/07

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#49]
07/02 - 05

- [x] https://github.com/rstudio/rticles/issues/178

**Comment by yihui** [comment]
07/10

- [x] Add icons for external links, e.g. https://rmarkdown.rstudio.com/formats.html

**Comment by yihui** [comment]
07/11

- [x] Abstract for the R Markdown workshop at rstudio::conf 2019.

**Comment by yihui** [comment]
07/13

- [x] Announce the R Markdown book in the blog.
- [x] 雪宁 R 书序

**Comment by yihui** [comment]
07/16 - 23

- [x] New bookdown.org website based on blogdown

**Comment by yihui** [comment]
07/24 - 26

- [x] Set up a bookdown contest.

**Comment by yihui** [comment]
07/27

- [ ] Improve animation support in knitr https://github.com/yihui/knitr/issues/762 https://github.com/yihui/animation/issues/118 https://github.com/thomasp85/gganimate
- [ ] Build TinyTeX for Windows/Ubuntu/macOS on the cloud.
- [ ] Use TinyTeX on Travis for macOS: https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
- [ ] An RStudio addin for bookdown to manage section IDs.
- [ ] https://github.com/rstudio/bookdown/issues/544
- [ ] Announce tinytex in RStudio blog.
- [ ] Typora
