### ISSUE TITLE
TODO 2018/08

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#53]
08/14

- [x] Build TinyTeX for Windows

**Comment by yihui** [comment]
08/16

- [x] Improve animation support in knitr https://github.com/yihui/knitr/issues/762 https://github.com/yihui/animation/issues/118 https://github.com/thomasp85/gganimate

**Comment by yihui** [comment]
08/20

- [x] Tweak the documentation of TinyTeX
- [x] Release a new version of tinytex to CRAN.

**Comment by yihui** [comment]
08/21

- [x] https://github.com/rstudio/rmarkdown/pull/1433
