### ISSUE TITLE
TODO 2018/10

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#59]
10/01

- [x] Change links to BootCDN resources (xaringan, bookdown, Hugo themes, etc)
- [x] more documentation of pagedown https://rstudio.github.io/pagedown

**Comment by yihui** [comment]
10/02- 05

- [x] Review bookdown contest submissions

**Comment by yihui** [comment]
10/09

- [x] release rticles

**Comment by yihui** [comment]
10/10

- [x] release evaluate

**Comment by yihui** [comment]
10/22

- [ ] An RStudio addin for bookdown to manage section IDs.
- [ ] https://github.com/rstudio/bookdown/issues/544
- [ ] Announce tinytex in RStudio blog.
- [ ] Note-taking/todo app https://d.cosx.org/d/419756-blogdown/10 https://noteplan.co https://everydaycheck.com
- [ ] Rbind RSS https://yufree.cn/cn/2018/03/24/blogdown-rss/
- [ ] DT DB interface
- [ ] Short videos

**Comment by yihui** [comment]
10/23

- [x] Release tinytex
- [x] Release xaringan after merging https://github.com/yihui/xaringan/pull/175
- [x] Release blogdown, servr, xfun

**Comment by yihui** [comment]
10/24

- [x] R Journal
- [x] https://github.com/rstudio/pagedown/pull/16

**Comment by yihui** [comment]
10/25

- [x] https://github.com/RelaxedJS/ReLaXed-examples/tree/master/examples/poster/
