### ISSUE TITLE
TODO 2018/12

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#63]
12/03

- [x] rstudio::conf talk
- [x] https://github.com/rstudio/bookdown/issues/544
- [x] Release bookdown to CRAN.

**Comment by yihui** [comment]
12/04 - 07

- [x] https://github.com/rstudio/rmarkdown/issues/1471
- [x] Triage rmarkdown issues for the next CRAN release.

**Comment by yihui** [comment]
12/10

- [x] CRAN releases of knitr and rmarkdown

**Comment by yihui** [comment]
12/11

- [x] https://github.com/yihui/xaringan/issues/185
- [x] `pagedown::poster_jacobs()`

**Comment by yihui** [comment]
12/12

- [ ] Plan pagedown release
- [ ] https://github.com/rstudio/rticles/pull/199
- [ ] https://github.com/ohrie/relaxed-resume
- [ ] An RStudio addin for bookdown to manage section IDs.
- [ ] Announce tinytex in RStudio blog.
- [ ] Note-taking/todo app https://d.cosx.org/d/419756-blogdown/10 https://noteplan.co https://everydaycheck.com
- [ ] Rbind RSS https://yufree.cn/cn/2018/03/24/blogdown-rss/
- [ ] DT DB interface
- [ ] Short videos
