### ISSUE TITLE
TODO 2019/08

### ISSUE THREAD

**Issue by yihui** [yihui/yihui.org#71]
08/12

- [x] Read the current draft: https://github.com/dr-harper/rmarkdown-cookbook
- [ ] Think more about chapter names.

**Comment by yihui** [comment]
08/13

- [x] Apply the CRC style and build the PDF.

**Comment by yihui** [comment]
08/14

- [x] Flatten Rmd files.

**Comment by yihui** [comment]
08/15

- [x] Section 2.1

**Comment by yihui** [comment]
08/16

- [ ] Write two recipes.
